### ISSUE TITLE
Usage Questions

### ISSUE THREAD

**Issue by vito-c** [scalameta/coc-metals#250]
### Fuzzy Finding
References:
Currently `coc` populates finding references to the location list. I think `coc` also has some builtin fuzzy finding that it's doing. I was wondering if it's possible to pump the results into `fzf` as I  use that for buffer/file searching already. 

Are there other places a fuzzy finder would be helpful?

### Testing
Is there anything similar to an LSP for testing? I think it would be really useful if there was a way to run tests via bloop builtin but maybe that's out of scope of this project?
I was thinking the following:
- run current file via <leader>tf (when you are on a test/spec)
- run current test case when you are on a specific test case <leader>tc
- if you are on a file in the app code maybe <leader>tf could the spec/test associated with it
- better formatting of test error respones similar to https://github.com/scalameta/coc-metals/issues/249
- there is a lot of other stuff I was thinking about around testing that might be useful I also have some settings that make jumping to files more seamless from the term that might be useful.

### Worksheets
I have a worksheet in `myapp/app/worksheet.sc` I can get completions and errors but when I try to `<leader>ws` to see the hidden results nothing happens. Did I make a mistake here?

### Completions
Is there something I need to set to  have this render nicer:
![image](https://user-images.githubusercontent.com/820137/87115478-4a584280-c228-11ea-85ee-7cff492ced64.png) I don't know when this started happening.

**Comment by ckipp01** [comment]
> I was wondering if it's possible to pump the results into fzf as I use that for buffer/file searching already.

So one of the things to keep in mind is that `coc-metals` really has no part or control in how this actually works. We're fully reliant on coc.nvim to receive in this case the references, and then display there. There are ways to hijack this and pump it to fzf actually. You can take a look at [`coc-fzf`](https://github.com/antoinemadec/coc-fzf) which is a pretty great extension for fzf users. It also looks like there has been some discussion about easily using other coc list alternatives [here](https://github.com/neoclide/coc.nvim/issues/307). So in short, there may be places where pumping the results to another "program" would work, but it'd be up to the user on configuring this, and I'd rather not make that choice for them inside of `coc-metals`.

> Is there anything similar to an LSP for testing?

So depending on what exactly you'd be looking for, [DAP](https://microsoft.github.io/debug-adapter-protocol/) will actually cover a lot of the stuff you're mentioning. 

> run current test case when you are on a specific test case tc

You should be able to already to this per suite with code lenses and vimspector.

> better formatting of test error respones similar to scalameta/coc-metals/issues/249

Are you referring to the test output in your terminal? If so, we have no control over that.

**Comment by vito-c** [comment]
Thanks! Isn't `DAP` more for debugging than running test/spec files? I guess there isn't really an easy way to identify test/spec files associated with a specific file.

**Comment by ckipp01** [comment]
> Thanks! Isn't DAP more for debugging than running test/spec files? I guess there isn't really an easy way to identify test/spec files associated with a specific file.

Yea, DAP is definitely more debugging focused, but also provides the other stuff we're talking about.

Also, sorry I totally forgot to answer the second half of your questions. Regarding the worksheets. Is this something that has stopped working for you, or have you never gotten it to work? After something evaluates, you need to ensure you're on the line of the evaluation. Are you sure you have the following in your vim config?

```vim
" Used to expand decorations in worksheets
nmap <leader>ws <Plug>(coc-metals-expand-decoration)
```

And regarding the rendering of your completions, that's also how I see them.

**Comment by vito-c** [comment]
> And regarding the rendering of your completions, that's also how I see them.
So is this a `coc.nvim` bug?

I was also wondering if you ever use snippets?  I used to use ultisnip but it  seems like coc wants me to use  their's .... I'm not really a fan of one tool doing everything...

**Comment by ckipp01** [comment]
> So is this a `coc.nvim` bug?

I don't think it's a bug per se. I actually don't remember every seeing them look different? I'd say throw that question in the coc.nvim gitter channel and they should be able to help with that.

> I was also wondering if you ever use snippets? I used to use ultisnip but it seems like coc wants me to use their's .... I'm not really a fan of one tool doing everything...

I don't use ultisnip since I don't really use snippets apart from LSP, and just use what coc.nvim provides.

**Comment by arbitrary-dev** [comment]
Do not want to create a separate ticket…

### Compilation

Is there a way to compile all sources to fill up workspace compile errors?

Because when I'm starting Vim on `build.sbt`, do `:CocCommand metals.[build-restart|compile-cascade]` and open workspace compile errors, there's nothing there, but `sbt test` fails with compilation errors.

**Comment by ckipp01** [comment]
So I'm going to close this to avoid confusing and to not just get continual question in here. @vito-c if you do have any other issues, questions, feel free to open an issue.

@arbitrary-dev, so if you have a fresh project, I'd recommend doing a `metals.clean-compile`. This will compile everything and fill up the drawer with your workspace errors.

**Comment by arbitrary-dev** [comment]
>[coc.nvim] Command: metals.clean-compile not found

**Comment by ckipp01** [comment]
@arbitrary-dev has metals started? What version of Metals and coc-metals are you using?

**Comment by arbitrary-dev** [comment]
>has metals started?
Yes, as far as I can see:
```
2020.08.03 13:03:04 INFO  started: Metals version 0.9.2 in workspace 'XXX' for client coc-metals.
2020.08.03 13:03:05 INFO  time: initialize in 0.93s
2020.08.03 13:03:05 INFO  no build target: using presentation compiler with only scala-library
2020.08.03 13:03:05 INFO  skipping build import with status 'Installed'
2020.08.03 13:03:11 INFO  time: connected to build server in 5.51s
2020.08.03 13:03:11 INFO  Connected to Build server v1.4.3
2020.08.03 13:03:11 INFO  time: imported build in 0.87s
2020.08.03 13:03:22 INFO  time: indexed workspace in 10s
```

>What version of Metals and coc-metals are you using?
```Metals version 0.9.2
coc-metals 0.9.1```

**Comment by ckipp01** [comment]
@arbitrary-dev how did you trigger it? For example, if you do a `<space> c` to open your commands, do you see `metals.compile-cascade` there?

**Comment by arbitrary-dev** [comment]
Ok, now I see, it's called `metals.compile-clean`, not `metals.clean-compile`.

Thanks :)

**Comment by ckipp01** [comment]
Ah my mistake! I also noticed I said `compile-cascade` above 😬 sorry.
